const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='luna-state-v1';
const defaultModels=[
{id:'nvidia/nemotron-3.5-lightning:free',name:'Nemotron 3.5 Lightning',desc:'高速・軽量な汎用モデル'},
{id:'nvidia/nemotron-3-ultra-550b-a55b:free',name:'Nemotron 3 Ultra',desc:'高性能な大規模モデル'},
{id:'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free',name:'Nemotron 3 Nano Omni',desc:'推論・マルチモーダル向け'},
{id:'google/gemma-4-26b-a4b-it:free',name:'Gemma 4 26B',desc:'高速で扱いやすい汎用モデル'},
{id:'nvidia/nemotron-3-super-120b-a12b:free',name:'Nemotron 3 Super',desc:'複雑なタスク向け'}
];
const defaults={chats:[],activeChat:null,settings:{model:defaultModels[0].id,name:'Takasi',callName:'',customInstructions:'',apiKey:'',theme:'light',accent:'default',font:'Inter / Noto Sans JP'}};
let state=loadState(),menuChat=null,pendingDelete=null,pendingRename=null,attachments=[];
function loadState(){try{const s=JSON.parse(localStorage.getItem(KEY));return s?{...defaults,...s,settings:{...defaults.settings,...s.settings}}:structuredClone(defaults)}catch{return structuredClone(defaults)}}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state))}
function uid(){return crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
function createChat(){const chat={id:uid(),title:'新しいチャット',messages:[],createdAt:Date.now(),updatedAt:Date.now()};state.chats.unshift(chat);state.activeChat=chat.id;saveState();renderChats();renderChat();return chat}
function activeChat(){return state.chats.find(c=>c.id===state.activeChat)||null}
function renderChats(){const el=$('#chatList');if(!el)return;el.innerHTML=state.chats.map(c=>`<div class="chat-item ${c.id===state.activeChat?'active':''}" data-id="${c.id}"><button class="chat-main" data-chat="${c.id}">${escapeHtml(c.title||'新しいチャット')}</button><button class="chat-more" data-more="${c.id}">•••</button></div>`).join('');$$('[data-chat]').forEach(b=>b.onclick=()=>selectChat(b.dataset.chat));$$('[data-more]').forEach(b=>b.onclick=e=>{e.stopPropagation();openContext(b.dataset.more,b)})}
function selectChat(id){if(!state.chats.some(c=>c.id===id))return;state.activeChat=id;saveState();renderChats();renderChat();closeContext()}
function renderChat(){const c=activeChat(),welcome=$('#welcome'),messages=$('#messages'),title=$('#chatTitle');if(!c){welcome.hidden=false;messages.hidden=true;title.textContent='新しいチャット';return}title.textContent=c.title||'新しいチャット';if(!c.messages.length){welcome.hidden=false;messages.hidden=true;return}welcome.hidden=true;messages.hidden=false;messages.innerHTML=c.messages.map((m,i)=>renderMessage(m,i)).join('');bindMessageActions()}
function renderMessage(m,i){if(m.role==='user')return `<article class="message user"><div class="bubble">${escapeHtml(m.content)}</div>${m.files?.length?`<div class="sent-files">${m.files.map(f=>`<span>${escapeHtml(f.name)}</span>`).join('')}</div>`:''}<div class="actions"><button data-edit="${i}">編集</button><button data-copy="${i}">コピー</button></div></article>`;return `<article class="message assistant"><div class="answer"><div class="answer-head"><span class="ai-mark">L</span><b>LUNA</b><span class="badge">AI</span></div><div class="answer-content">${m.html||escapeHtml(m.content).replace(/\n/g,'<br>')}</div><div class="answer-actions"><button data-copy="${i}">コピー</button><button data-regenerate="${i}">再生成</button></div></div></article>`}
function bindMessageActions(){$$('[data-copy]').forEach(b=>b.onclick=async()=>{const m=activeChat()?.messages[+b.dataset.copy];if(m)try{await navigator.clipboard.writeText(m.content);toast('コピーしました')}catch{toast('コピーに失敗しました')}});$$('[data-edit]').forEach(b=>b.onclick=()=>{const m=activeChat()?.messages[+b.dataset.edit];if(m){$('#prompt').value=m.content;resizePrompt();$('#prompt').focus()}});$$('[data-regenerate]').forEach(b=>b.onclick=()=>toast('再生成はAPI接続後に有効になります'))}
function sendMessage(text){text=(text??$('#prompt').value).trim();if(!text&&!attachments.length)return;if(!activeChat())createChat();const c=activeChat(),files=attachments.map(f=>({name:f.name,size:f.size,type:f.type}));c.messages.push({role:'user',content:text,files});if(c.title==='新しいチャット'&&text)c.title=text.length>32?text.slice(0,32)+'…':text;c.updatedAt=Date.now();saveState();attachments=[];renderAttachments();renderChat();$('#prompt').value='';resizePrompt();setTimeout(()=>demoAnswer(c),350)}
function demoAnswer(c){if(activeChat()?.id!==c.id)return;c.messages.push({role:'assistant',content:'これは現在のUI動作確認用のデモ応答です。OpenRouter APIを接続すると、ここが実際のAI応答になります。',html:'<p>これは現在のUI動作確認用のデモ応答です。</p><p>OpenRouter APIを接続すると、ここが実際のAI応答になります。</p>'});c.updatedAt=Date.now();saveState();renderChat()}
function openContext(id,anchor){menuChat=id;const x=anchor.getBoundingClientRect(),el=$('#context');el.classList.add('show');el.style.position='fixed';el.style.left=Math.min(x.right-150,innerWidth-158)+'px';el.style.top=Math.min(x.bottom+4,innerHeight-90)+'px'}
function closeContext(){$('#context')?.classList.remove('show');menuChat=null}
function openRename(id){const c=state.chats.find(x=>x.id===id);if(!c)return;pendingRename=id;const input=$('#renameInput');input.value=c.title||'';$('#renameBackdrop').classList.add('show');closeContext();requestAnimationFrame(()=>{input.focus();input.select()})}
function saveRename(){const c=state.chats.find(x=>x.id===pendingRename),input=$('#renameInput');if(!c||!input)return;const name=input.value.trim();if(!name){input.focus();return}c.title=name.slice(0,80);c.updatedAt=Date.now();saveState();renderChats();renderChat();closeRename();toast('チャット名を変更しました')}
function closeRename(){pendingRename=null;$('#renameBackdrop')?.classList.remove('show')}
function askDelete(id){const c=state.chats.find(x=>x.id===id);if(!c)return;pendingDelete=id;$('#confirmTitle').textContent='チャットを削除しますか？';$('#confirmText').textContent=`「${c.title||'新しいチャット'}」を削除します。この操作は元に戻せません。`;$('#confirmBackdrop').classList.add('show');closeContext()}
function deleteChat(){if(!pendingDelete)return;const idx=state.chats.findIndex(c=>c.id===pendingDelete);state.chats=state.chats.filter(c=>c.id!==pendingDelete);if(state.activeChat===pendingDelete)state.activeChat=state.chats[Math.max(0,idx-1)]?.id||null;pendingDelete=null;saveState();$('#confirmBackdrop').classList.remove('show');renderChats();renderChat()}
function populateModels(){const menu=$('#modelMenu');if(menu)menu.innerHTML=defaultModels.map(m=>`<button class="model-option ${m.id===state.settings.model?'selected':''}" data-model="${m.id}"><span class="dot"></span><div><b>${m.name}</b><small>${m.desc}</small></div></button>`).join('');$$('[data-model]').forEach(b=>b.onclick=()=>{state.settings.model=b.dataset.model;saveState();applySettings();closeModel()});const s=$('#settingsModel');if(s){s.innerHTML=defaultModels.map(m=>`<option value="${m.id}">${m.name}</option>`).join('');s.value=state.settings.model}}
function applySettings(){const m=defaultModels.find(x=>x.id===state.settings.model)||defaultModels[0];$('#modelLabel').textContent=m.name;if($('#settingsModel'))$('#settingsModel').value=state.settings.model;document.documentElement.dataset.theme=state.settings.theme;document.documentElement.dataset.accent=state.settings.accent;document.documentElement.style.setProperty('--font-ui',state.settings.font)}
function closeModel(){$('#modelMenu')?.classList.remove('show')}
function openSettings(){$('#settingsBackdrop').classList.add('show');loadSettingsFields()}
function loadSettingsFields(){const s=state.settings;if($('#accountName'))$('#accountName').value=s.name;if($('#personalName'))$('#personalName').value=s.callName||'';if($('#customInstructions'))$('#customInstructions').value=s.customInstructions||'';if($('#apiKey'))$('#apiKey').value=s.apiKey||'';applySettings()}
function saveSettingsFields(){const s=state.settings;if($('#accountName'))s.name=$('#accountName').value.trim()||'Takasi';if($('#personalName'))s.callName=$('#personalName').value.trim();if($('#customInstructions'))s.customInstructions=$('#customInstructions').value;if($('#apiKey'))s.apiKey=$('#apiKey').value.trim();if($('#settingsModel'))s.model=$('#settingsModel').value;if($('#fontSelect'))s.font=$('#fontSelect').value;saveState();applySettings()}
function renderAttachments(){const el=$('#attachments');if(!el)return;el.innerHTML=attachments.map((f,i)=>`<div class="attachment"><div class="thumb">${f.type?.startsWith('image/')&&f.url?`<img src="${f.url}" alt="">`:escapeHtml((f.name.split('.').pop()||'FILE').toUpperCase())}</div><div class="file-meta"><b>${escapeHtml(f.name)}</b><small>${formatSize(f.size)}</small></div><button class="remove-file" data-remove-file="${i}">×</button></div>`).join('');$$('[data-remove-file]').forEach(b=>b.onclick=()=>{attachments.splice(+b.dataset.removeFile,1);renderAttachments()})}
function addFiles(files){[...files].forEach(f=>attachments.push({name:f.name,size:f.size,type:f.type,url:f.type?.startsWith('image/')?URL.createObjectURL(f):null}));renderAttachments();closeFile()}
function closeFile(){$('#fileMenu')?.classList.remove('show');$('#fileOverlay')?.classList.remove('show')}
function resizePrompt(){const p=$('#prompt');if(p){p.style.height='auto';p.style.height=Math.min(p.scrollHeight,170)+'px'}}
function toast(t){const el=$('#toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatSize(n){if(n<1024)return n+' B';if(n<1048576)return Math.round(n/1024)+' KB';return (n/1048576).toFixed(1)+' MB'}
if(!state.chats.length)createChat();else if(!state.activeChat||!state.chats.some(c=>c.id===state.activeChat))state.activeChat=state.chats[0].id;
renderChats();renderChat();populateModels();applySettings();
$('#newChat')?.addEventListener('click',createChat);$('#homeBtn')?.addEventListener('click',()=>{if(!activeChat()||activeChat().messages.length)createChat();else renderChat()});$('#send')?.addEventListener('click',()=>sendMessage());$('#prompt')?.addEventListener('input',resizePrompt);$('#prompt')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});
$$('.suggestions button').forEach(b=>b.onclick=()=>{$('#prompt').value=b.textContent;resizePrompt();$('#prompt').focus()});
$('#modelBtn')?.addEventListener('click',e=>{e.stopPropagation();$('#modelMenu').classList.toggle('show')});document.addEventListener('click',e=>{if(!e.target.closest('#modelBtn')&&!e.target.closest('#modelMenu'))closeModel();if(!e.target.closest('#context'))closeContext()});
$('#delete')?.addEventListener('click',()=>askDelete(menuChat));$('#rename')?.addEventListener('click',()=>openRename(menuChat));$('#cancelDelete')?.addEventListener('click',()=>{$('#confirmBackdrop').classList.remove('show');pendingDelete=null});$('#doDelete')?.addEventListener('click',deleteChat);$('#confirmBackdrop')?.addEventListener('click',e=>{if(e.target.id==='confirmBackdrop'){$('#confirmBackdrop').classList.remove('show');pendingDelete=null}});
$('#saveRename')?.addEventListener('click',saveRename);$('#cancelRename')?.addEventListener('click',closeRename);$('#renameBackdrop')?.addEventListener('click',e=>{if(e.target.id==='renameBackdrop')closeRename()});$('#renameInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')saveRename();if(e.key==='Escape')closeRename()});
$('#settingsOpen')?.addEventListener('click',openSettings);$('#settingsClose')?.addEventListener('click',()=>{$('#settingsBackdrop').classList.remove('show');saveSettingsFields()});$('#settingsBackdrop')?.addEventListener('click',e=>{if(e.target.id==='settingsBackdrop'){$('#settingsBackdrop').classList.remove('show');saveSettingsFields()}});$('#settingsModel')?.addEventListener('change',saveSettingsFields);$('#apiKey')?.addEventListener('change',saveSettingsFields);$('#accountName')?.addEventListener('change',saveSettingsFields);$('#personalName')?.addEventListener('change',saveSettingsFields);$('#customInstructions')?.addEventListener('change',saveSettingsFields);$('#fontSelect')?.addEventListener('change',saveSettingsFields);
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-page]').forEach(p=>p.classList.toggle('active',p.dataset.page===b.dataset.tab))});
$('#pickFiles')?.addEventListener('click',()=>$('#fileInput').click());$('#cameraFiles')?.addEventListener('click',()=>{const i=$('#fileInput');i.setAttribute('accept','image/*');i.click()});$('#fileInput')?.addEventListener('change',e=>{addFiles(e.target.files);e.target.value=''});$('#demoFile')?.addEventListener('click',()=>{attachments.push({name:'LUNA-demo.txt',size:1842,type:'text/plain'});renderAttachments();closeFile()});
$('#attach')?.addEventListener('click',e=>{e.stopPropagation();$('#fileMenu').classList.toggle('show');$('#fileOverlay').classList.toggle('show')});$('#webBtn')?.addEventListener('click',()=>{$('#webBtn').classList.toggle('selected');toast($('#webBtn').classList.contains('selected')?'Web検索を有効化':'Web検索を無効化')});$('#openSide')?.addEventListener('click',()=>$('#sidebar')?.classList.add('open'));$('#closeSide')?.addEventListener('click',()=>$('#sidebar')?.classList.remove('open'));$('#conversation')?.addEventListener('click',()=>$('#sidebar')?.classList.remove('open'));$('#moreBtn')?.addEventListener('click',()=>toast('チャット操作メニュー'));$('#demoToggle')?.addEventListener('click',()=>$('#showcaseBackdrop')?.classList.add('show'));$('#showcaseClose')?.addEventListener('click',()=>$('#showcaseBackdrop')?.classList.remove('show'));$('#showcaseBackdrop')?.addEventListener('click',e=>{if(e.target.id==='showcaseBackdrop')e.currentTarget.classList.remove('show')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeFile();closeModel();closeContext();$('#confirmBackdrop')?.classList.remove('show');closeRename();$('#settingsBackdrop')?.classList.remove('show');$('#showcaseBackdrop')?.classList.remove('show')}});
