const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const models=[
{name:'Nemotron 3.5 Lightning',id:'nvidia/nemotron-3.5-lightning:free',desc:'高速・軽量。普段の会話や素早い回答に向いています。'},
{name:'Nemotron 3 Ultra',id:'nvidia/nemotron-3-ultra-550b-a55b:free',desc:'高性能推論。複雑な質問や難しいタスク向けです。'},
{name:'Nemotron 3 Nano Omni',id:'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free',desc:'マルチモーダル推論。画像などを扱う用途に向いています。'},
{name:'Gemma 4 26B',id:'google/gemma-4-26b-a4b-it:free',desc:'バランス型。日常会話から一般的な質問まで幅広く対応します。'},
{name:'Nemotron 3 Super',id:'nvidia/nemotron-3-super-120b-a12b:free',desc:'高性能汎用。複雑な指示や難しいタスク向けです。'}];
let chats=[{id:1,title:'新しいチャット'},{id:2,title:'アイデアを整理する'},{id:3,title:'Webアプリの設計について'},{id:4,title:'今日のメモ'}],active=1,contextChat=null,attachments=[];
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}
function renderChats(){const box=$('#chatList');box.innerHTML=chats.map(c=>`<div class="chat-item ${c.id===active?'active':''}"><button class="chat-main">${esc(c.title)}</button><button class="chat-more" aria-label="メニュー">•••</button></div>`).join('');$$('.chat-main').forEach((b,i)=>b.onclick=()=>selectChat(chats[i].id));$$('.chat-more').forEach((b,i)=>b.onclick=e=>{e.stopPropagation();openContext(b,chats[i].id)})}
function selectChat(id){active=id;const c=chats.find(x=>x.id===id);if(c)$('#chatTitle').textContent=c.title;renderChats();if(innerWidth<=760)$('#sidebar').classList.remove('open')}
function closeMenus(){$('#modelMenu')?.classList.remove('show');$('#context')?.classList.remove('show');closeFile()}
function openContext(btn,id){contextChat=id;const m=$('#context'),r=btn.getBoundingClientRect();m.style.left=Math.min(r.left,innerWidth-160)+'px';m.style.top=Math.min(r.bottom+4,innerHeight-90)+'px';m.classList.add('show')}
renderChats();
$('#newChat').onclick=()=>{const id=Date.now();chats.unshift({id,title:'新しいチャット'});selectChat(id);$('#welcome').hidden=false;$('#messages').hidden=true;$('#prompt').focus()};
$('#homeBtn').onclick=()=>{$('#welcome').hidden=false;$('#messages').hidden=true};
$('#openSide').onclick=()=>$('#sidebar').classList.add('open');$('#closeSide').onclick=()=>$('#sidebar').classList.remove('open');
$('#main')?.addEventListener('click',e=>{if(innerWidth<=760&&!e.target.closest('#sidebar'))$('#sidebar').classList.remove('open')});
$('#rename').onclick=()=>{const c=chats.find(x=>x.id===contextChat);if(!c)return;const n=prompt('チャット名',c.title);if(n?.trim()){c.title=n.trim();selectChat(c.id)}$('#context').classList.remove('show')};
$('#delete').onclick=()=>{const c=chats.find(x=>x.id===contextChat);if(!c)return;$('#confirmTitle').textContent=`「${c.title}」を削除しますか？`;$(`#confirmText`).textContent='このチャットと会話内容は元に戻せません。';$('#confirmBackdrop').classList.add('show');$('#context').classList.remove('show')};
$('#cancelDelete').onclick=()=>$('#confirmBackdrop').classList.remove('show');$('#doDelete').onclick=()=>{chats=chats.filter(c=>c.id!==contextChat);if(!chats.length)chats=[{id:Date.now(),title:'新しいチャット'}];active=chats[0].id;selectChat(active);$('#confirmBackdrop').classList.remove('show');toast('チャットを削除しました')};
function renderModels(){const menu=$('#modelMenu');menu.innerHTML=models.map((m,i)=>`<button class="model-option ${i===0?'selected':''}" data-i="${i}"><span class="dot"></span><div><b>${esc(m.name)}</b><small>${esc(m.desc)}</small></div></button>`).join('');$$('.model-option').forEach(b=>b.onclick=()=>{const m=models[+b.dataset.i];$('#modelLabel').textContent=m.name;$$('.model-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');menu.classList.remove('show');toast(`${m.name}を選択しました`)});$('#settingsModel').innerHTML=models.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}
renderModels();$('#modelBtn').onclick=e=>{e.stopPropagation();$('#modelMenu').classList.toggle('show')};
function closeFile(){$('#fileMenu')?.classList.remove('show');$('#fileOverlay')?.classList.remove('show')}
$('#attach').onclick=e=>{e.stopPropagation();$('#fileMenu').classList.add('show');$('#fileOverlay').classList.add('show')};$('#fileOverlay').onclick=closeFile;
$('#pickFiles').onclick=()=>{$('#fileInput').click();closeFile()};$('#cameraFiles').onclick=()=>{$('#fileInput').click();closeFile()};$('#demoFile').onclick=()=>{addDemoFiles();closeFile()};
$('#fileInput').onchange=e=>{[...e.target.files].forEach(addFile);e.target.value=''};
function addDemoFiles(){[new File(['<h1>LUNA Preview</h1>'],'luna-preview.html',{type:'text/html'}),new File(['name,status\nLUNA,ready'],'result.csv',{type:'text/csv'}),new File(['{"status":"ready"}'],'data.json',{type:'application/json'})].forEach(addFile);toast('デモファイルを追加しました')}
function addFile(file){attachments.push({id:Date.now()+Math.random(),file});renderAttachments()}
function fileIcon(f){if(f.type==='application/pdf'||/\.pdf$/i.test(f.name))return'PDF';if(f.type==='text/html')return'HTML';if(f.type==='text/csv')return'CSV';if(f.type==='application/json')return'JSON';return'FILE'}
function fileType(f){if(f.type.startsWith('image/'))return'画像';if(f.type==='application/pdf')return'PDF';if(f.type==='text/html')return'HTML';return'ドキュメント'}
function fileSize(n){return n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB'}
function renderAttachments(){const box=$('#attachments');box.innerHTML=attachments.map(a=>{const f=a.file,img=f.type.startsWith('image/');return `<div class="attachment"><span class="thumb">${img?`<img src="${URL.createObjectURL(f)}" alt="">`:fileIcon(f)}</span><span class="file-meta"><b>${esc(f.name)}</b><small>${fileSize(f.size)} · ${fileType(f)}</small></span><button class="remove-file" data-id="${a.id}">×</button></div>`}).join('');$$('.remove-file').forEach(b=>b.onclick=()=>{attachments=attachments.filter(a=>String(a.id)!==b.dataset.id);renderAttachments()})}
['dragenter','dragover'].forEach(ev=>$('#composer').addEventListener(ev,e=>{e.preventDefault();$('#dropHint').classList.add('show')}));['dragleave','drop'].forEach(ev=>$('#composer').addEventListener(ev,e=>{e.preventDefault();$('#dropHint').classList.remove('show')}));$('#composer').addEventListener('drop',e=>[...e.dataTransfer.files].forEach(addFile));
const promptBox=$('#prompt');promptBox.addEventListener('input',()=>{promptBox.style.height='auto';promptBox.style.height=Math.min(promptBox.scrollHeight,170)+'px'});promptBox.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$$('.suggestions button').forEach(b=>b.onclick=()=>{promptBox.value=b.textContent;promptBox.dispatchEvent(new Event('input'));promptBox.focus()});$('#send').onclick=send;
function send(){const text=promptBox.value.trim();if(!text&&!attachments.length)return;$('#welcome').hidden=true;$('#messages').hidden=false;const list=$('#messages');const user=document.createElement('article');user.className='message user';user.innerHTML=`<div class="bubble">${esc(text||'添付ファイルを送信しました。')}</div>${attachments.length?`<div class="sent-files">${attachments.map(a=>`<span>${esc(a.file.name)}</span>`).join('')}</div>`:''}<div class="actions"><button data-edit>✎ 編集</button><button data-copy>□ コピー</button></div>`;list.appendChild(user);const ai=document.createElement('article');ai.className='message ai';ai.innerHTML=demoAnswer();list.appendChild(ai);promptBox.value='';promptBox.style.height='auto';attachments=[];renderAttachments();bindMessageActions(user);bindMessageActions(ai);list.parentElement.scrollTop=list.parentElement.scrollHeight}
function demoAnswer(){return `<div class="answer"><div class="answer-head"><span class="ai-mark">L</span><b>LUNA</b><span class="badge">回答</span></div><h2>UIプレビューのサンプル</h2><p>これはLUNAの完成UIを確認するためのサンプル回答です。<strong>Markdown</strong>、引用、表、コード、ファイル出力を確認できます。</p><blockquote>重要な情報は一次情報を確認してください。</blockquote><h3>チェックリスト</h3><ul><li>Markdown表示</li><li>コードブロックとコピー</li><li>表とリンク</li><li>生成ファイル</li></ul><div class="code-card"><div class="code-head"><span>javascript</span><div><button data-copy-code>コピー</button><button data-download-code>ダウンロード</button></div></div><pre><code>const luna = {\n  status: 'ready',\n  ui: 'complete'\n};</code></pre></div><div class="table-card"><table><thead><tr><th>項目</th><th>状態</th><th>説明</th></tr></thead><tbody><tr><td>UI</td><td><span class="ok">完成</span></td><td>レビュー可能</td></tr><tr><td>API</td><td><span class="pending">未接続</span></td><td>次工程</td></tr></tbody></table></div><div class="preview-card"><div><span class="preview-icon">HTML</span><div><b>luna-preview.html</b><small>HTMLファイル · 2.4 KB</small></div></div><div class="preview-actions"><button data-preview>プレビュー</button><button data-download>↓ ダウンロード</button></div></div><div class="source-box"><div><b>Sources</b><small>Web検索結果をここに表示します</small></div><button data-sources>3件を見る ›</button></div><div class="answer-actions"><button data-regenerate>↻ 再生成</button><button data-copy>□ コピー</button><button data-sources>Sources</button></div></div>`}
function bindMessageActions(root){$$('[data-copy],[data-copy-code]',root).forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText('LUNA UI sample');toast('コピーしました')});$$('[data-edit]',root).forEach(b=>b.onclick=()=>{const text=root.querySelector('.bubble')?.textContent||'';promptBox.value=text;promptBox.dispatchEvent(new Event('input'));promptBox.focus();toast('編集欄に戻しました')});$$('[data-download],[data-download-code]',root).forEach(b=>b.onclick=downloadFile);$$('[data-preview]',root).forEach(b=>b.onclick=openPreview);$$('[data-regenerate]',root).forEach(b=>b.onclick=()=>{toast('回答を再生成しています…');setTimeout(()=>toast('新しい回答を生成しました'),700)});$$('[data-sources]',root).forEach(b=>b.onclick=()=>toast('SourcesパネルはWeb検索接続後に表示されます'))}
function downloadFile(){const blob=new Blob(['<h1>LUNA Preview</h1><p>生成HTMLのプレビューです。</p>'],{type:'text/html'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='luna-preview.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast('ダウンロードを開始しました')}
function openPreview(){const w=window.open('','_blank','width=700,height=600');if(w){w.document.write('<!doctype html><title>LUNA Preview</title><style>body{font:16px system-ui;padding:40px}h1{font-size:32px}</style><h1>LUNA Preview</h1><p>生成HTMLのプレビューです。</p>');w.document.close()}}
$('#webBtn').onclick=()=>{$('#webBtn').classList.toggle('selected');toast($('#webBtn').classList.contains('selected')?'Web検索を有効化':'Web検索を無効化')};
$('#settingsOpen').onclick=()=>$('#settingsBackdrop').classList.add('show');$('#settingsClose').onclick=()=>$('#settingsBackdrop').classList.remove('show');$('#settingsBackdrop').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.classList.remove('show')};
$$('#settingsTabs button').forEach(t=>t.onclick=()=>{$$('#settingsTabs button').forEach(x=>x.classList.remove('active'));$$('.settings-page').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(`.settings-page[data-page="${t.dataset.tab}"]`)?.classList.add('active')});
$$('.swatch').forEach(s=>s.onclick=()=>{$$('.swatch').forEach(x=>x.classList.remove('selected'));s.classList.add('selected');toast('アクセントカラーを選択しました')});$$('.segmented button').forEach(b=>b.onclick=()=>{$$('.segmented button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');toast(`${b.textContent}テーマを選択しました`)});
$('#demoToggle').onclick=()=>{renderShowcase();$('#showcaseBackdrop').classList.add('show')};$('#showcaseClose').onclick=()=>$('#showcaseBackdrop').classList.remove('show');$('#showcaseBackdrop').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.classList.remove('show')};
function renderShowcase(){const b=$('#showcaseBody');b.innerHTML=`<div class="showcase-grid"><section><h3>モデル</h3><div class="demo-panel">${models.map(m=>`<div class="demo-model"><span class="dot"></span><div><b>${esc(m.name)}</b><small>${esc(m.desc)}</small></div></div>`).join('')}</div></section><section><h3>回答表示</h3><div class="demo-panel">${demoAnswer()}</div></section><section><h3>ファイル状態</h3><div class="demo-panel file-states"><div class="state"><b>アップロード</b><span>PDF / 画像 / コード</span></div><div class="state loading"><b>読み込み中</b><span>ファイルを解析しています…</span></div><div class="state error"><b>読み込み失敗</b><span>ファイルを読み込めませんでした</span></div><div class="state success"><b>完了</b><span>内容を読み取りました</span></div></div></section><section><h3>入力・検索</h3><div class="demo-panel"><div class="fake-input">LUNAにメッセージを入力…<button>↑</button></div><div class="source-box"><div><b>Web Sources</b><small>検索結果カードの表示</small></div><button>開く ›</button></div></div></section><section><h3>空・ローディング・エラー</h3><div class="demo-panel states"><div class="empty-state"><b>まだ会話はありません</b><small>新しいチャットを始めましょう。</small></div><div class="thinking"><span></span><span></span><span></span><b>考えています…</b></div><div class="error-state"><b>回答を取得できませんでした</b><button>再試行</button></div></div></section></div>`;$$('[data-copy],[data-copy-code],[data-download],[data-download-code],[data-preview],[data-regenerate],[data-sources]',b).forEach(x=>bindMessageActions(b))}
document.addEventListener('click',e=>{if(!e.target.closest('#modelBtn')&&!e.target.closest('#modelMenu'))$('#modelMenu')?.classList.remove('show');if(!e.target.closest('.chat-more')&&!e.target.closest('#context'))$('#context')?.classList.remove('show')});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#newChat').click()}if(e.key==='Escape'){['#settingsBackdrop','#confirmBackdrop','#showcaseBackdrop'].forEach(s=>$(s)?.classList.remove('show'));closeMenus()}});
