const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const models=[['Nemotron 3.5 Lightning','nvidia/nemotron-3.5-lightning:free'],['Nemotron 3 Ultra 550B','nvidia/nemotron-3-ultra-550b-a55b:free'],['Nemotron 3 Nano Omni 30B Reasoning','nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free'],['Gemma 4 26B A4B IT','google/gemma-4-26b-a4b-it:free'],['Nemotron 3 Super 120B','nvidia/nemotron-3-super-120b-a12b:free']];
let chats=[{id:1,title:'新しいチャット'},{id:2,title:'アイデアを整理する'},{id:3,title:'Webアプリの設計について'},{id:4,title:'今日のメモ'}];let activeChat=1;let contextChat=null;let attachments=[];
const chatList=$('#chatList');function renderChats(){chatList.innerHTML='';chats.forEach(c=>{const el=document.createElement('div');el.className='chat-item'+(c.id===activeChat?' active':'');el.innerHTML=`<button class="chat-item-main" style="display:block;width:100%;text-align:left;padding:12px 5px;font-size:13px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${escapeHtml(c.title)}</button><button class="chat-more" aria-label="チャットメニュー">•••</button>`;el.querySelector('.chat-item-main').onclick=()=>selectChat(c.id);el.querySelector('.chat-more').onclick=e=>{e.stopPropagation();openContext(e.currentTarget,c.id)};chatList.appendChild(el)})}function selectChat(id){activeChat=id;const c=chats.find(x=>x.id===id);$('#topbarTitle').textContent=c.title;renderChats();if(innerWidth<=760)$('#sidebar').classList.remove('open')}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
renderChats();
$('#newChat').onclick=()=>{const id=Date.now();chats.unshift({id,title:'新しいチャット'});selectChat(id);$('#welcome').hidden=false;$('#messages').hidden=true};
$('#menuButton').onclick=()=>$('#sidebar').classList.add('open');$('#closeSidebar').onclick=()=>$('#sidebar').classList.remove('open');$('#main').onclick=e=>{if(innerWidth<=760&&!e.target.closest('.sidebar'))$('#sidebar').classList.remove('open')};
function openContext(btn,id){contextChat=id;const m=$('#contextMenu');const r=btn.getBoundingClientRect();m.style.left=Math.min(r.left,innerWidth-165)+'px';m.style.top=Math.min(r.bottom+4,innerHeight-100)+'px';m.style.display='block'}document.addEventListener('click',e=>{if(!e.target.closest('.chat-more')&&!e.target.closest('.context-menu'))$('#contextMenu').style.display='none'});
$('#renameChat').onclick=()=>{const c=chats.find(x=>x.id===contextChat);const n=prompt('チャット名',c.title);if(n?.trim()){c.title=n.trim();selectChat(c.id)}$('#contextMenu').style.display='none'};$('#deleteChat').onclick=()=>{const c=chats.find(x=>x.id===contextChat);$('#confirmTitle').textContent=`「${c.title}」を削除しますか？`;$('#confirmText').textContent='このチャットと会話内容は元に戻せません。';$('#confirmBackdrop').style.display='flex';$('#contextMenu').style.display='none'};$('#confirmCancel').onclick=()=>$('#confirmBackdrop').style.display='none';$('#confirmDelete').onclick=()=>{chats=chats.filter(c=>c.id!==contextChat);if(!chats.length)chats=[{id:Date.now(),title:'新しいチャット'}];activeChat=chats[0].id;selectChat(activeChat);$('#confirmBackdrop').style.display='none'};
const modelMenu=$('#modelMenu');modelMenu.innerHTML=models.map((m,i)=>`<button class="model-option ${i===0?'selected':''}" data-model="${i}"><span class="status-dot"></span><div><strong>${m[0]}</strong><small>${m[1]}</small></div></button>`).join('');$('#modelButton').onclick=e=>{e.stopPropagation();modelMenu.style.display=modelMenu.style.display==='block'?'none':'block'};$$('.model-option').forEach(b=>b.onclick=()=>{const m=models[+b.dataset.model];$('#modelLabel').textContent=m[0];$$('.model-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');modelMenu.style.display='none'});
$('#attachButton').onclick=e=>{e.stopPropagation();$('#fileMenu').style.display='block';$('#popoverOverlay').style.display='block'};$('#popoverOverlay').onclick=closeFileMenu;function closeFileMenu(){$('#fileMenu').style.display='none';$('#popoverOverlay').style.display='none'};$$('#fileMenu button').forEach(b=>b.onclick=()=>{$('#fileInput').click();closeFileMenu()});$('#fileInput').onchange=e=>{[...e.target.files].forEach(addAttachment);e.target.value=''};
function addAttachment(file){const id=Date.now()+Math.random();attachments.push({id,file});renderAttachments()}function renderAttachments(){const box=$('#attachmentStrip');box.innerHTML='';attachments.forEach(a=>{const f=a.file;const image=f.type.startsWith('image/');const url=image?URL.createObjectURL(f):'';const el=document.createElement('button');el.className='attachment-card';el.innerHTML=`<span class="attachment-thumb">${image?`<img src="${url}" alt="">`:f.type==='application/pdf'?'PDF':'TXT'}</span><span class="attachment-info"><strong>${escapeHtml(f.name)}</strong><small>${formatSize(f.size)} · ${image?'画像':'ドキュメント'}</small></span><span class="attachment-remove">×</span>`;el.onclick=()=>previewAttachment(a);el.querySelector('.attachment-remove').onclick=e=>{e.stopPropagation();attachments=attachments.filter(x=>x.id!==a.id);renderAttachments()};box.appendChild(el)})}function formatSize(n){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`}function previewAttachment(a){alert(`プレビュー: ${a.file.name}\n\n実装段階ではここにPDFビューアー/画像ビューアーを表示します。`)}
const prompt=$('#prompt');prompt.addEventListener('input',()=>{prompt.style.height='auto';prompt.style.height=Math.min(prompt.scrollHeight,180)+'px'});prompt.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});$('#sendButton').onclick=sendMessage;function sendMessage(){const text=prompt.value.trim();if(!text&&!attachments.length)return;$('#welcome').hidden=true;$('#messages').hidden=false;const list=$('#messages');const user=document.createElement('article');user.className='message user';user.innerHTML=`<div class="bubble">${escapeHtml(text||'添付ファイルを送信しました。')}</div><div class="message-actions"><button class="mini-action">✎ 編集</button><button class="mini-action">□ コピー</button></div>`;list.appendChild(user);const ai=document.createElement('article');ai.className='message ai';ai.innerHTML=`<div class="bubble"><strong>LUNA</strong><p>これはUIプレビュー用のサンプル回答です。Markdown、コードブロック、テーブル、ファイル出力、Web検索ソースなどの表示領域をここに統合できます。</p><pre><code>const luna = 'ready';</code></pre><div class="demo-table"><table><tr><th>項目</th><th>状態</th></tr><tr><td>UI</td><td>完成</td></tr><tr><td>API</td><td>接続予定</td></tr></table></div><div class="source-card"><span>⌕</span><div><strong>Sources</strong><small>Web検索結果がここに表示されます</small></div><span>›</span></div><div class="file-output"><span>HTML</span><strong>luna-preview.html</strong><button>↓ ダウンロード</button><button>プレビュー</button></div></div><div class="message-actions"><button class="mini-action">↻ 再生成</button><button class="mini-action">□ コピー</button><button class="mini-action">Sources</button></div>`;list.appendChild(ai);prompt.value='';prompt.style.height='auto';attachments=[];renderAttachments();list.parentElement.scrollTop=list.parentElement.scrollHeight}
$('#searchToggle').onclick=()=>$('#searchToggle').classList.toggle('selected');
$('#openSettings').onclick=()=>$('#settingsBackdrop').style.display='flex';$('#closeSettings').onclick=()=>$('#settingsBackdrop').style.display='none';$('#settingsBackdrop').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.style.display='none'};$$('.settings-tab').forEach(tab=>tab.onclick=()=>{$$('.settings-tab').forEach(x=>x.classList.remove('active'));$$('.settings-page').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(`.settings-page[data-page="${tab.dataset.tab}"]`).classList.add('active')});
$('#topMore').onclick=()=>$('#openSettings').click();document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#newChat').click()}if(e.key==='Escape'){ $('#settingsBackdrop').style.display='none';$('#confirmBackdrop').style.display='none';$('#contextMenu').style.display='none';closeFileMenu()}});